services:
  InstagramToMealie:
    build:
      context: .
      dockerfile: Dockerfile
    image: instagramtomealie:latest
    ports:
      - 9001:9001
    environment:
      INSTA_USER: "instagram username"
      MEALIE_API_KEY: "MEALIE API KEY"
      MEALIE_URL: "YOU LOCAL MEALIE INSTALLATION"
      MEALIE_OPENAI_REQUEST_TIMEOUT: 360
    volumes:
      - ./session-file:/app/session-file
